const BASE_METADATA = {
  llmVisible: true,
  contextRequirements: ['userId'],
}

const buildTool = (tool) => ({
  ...BASE_METADATA,
  dangerous: false,
  confirmationPolicy: 'never',
  uiLabel: tool.name,
  resultPresenter: `${tool.domain}.${tool.mode}.${tool.name}ResultPresenter`,
  confirmationDescriptor: null,
  ...tool,
})

const TOOL_CATALOG = [
  buildTool({
    name: 'get_user_profile',
    domain: 'profile',
    mode: 'read',
    uiLabel: '用户画像',
    description: '获取当前登录用户的基础画像信息（用于排查/引导与个性化建议）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    handler: 'profile.read.getUserProfile',
  }),
  buildTool({
    name: 'get_profile_insight',
    domain: 'profile',
    mode: 'read',
    uiLabel: '偏好洞察',
    description: '获取当前登录用户的长期风格画像、偏好标签与确认偏好',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    handler: 'profile.read.getProfileInsight',
  }),
  buildTool({
    name: 'get_wardrobe_analytics',
    domain: 'profile',
    mode: 'read',
    uiLabel: '衣橱统计',
    description: '获取当前登录用户的衣橱统计分析结果',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    handler: 'profile.read.getWardrobeAnalytics',
  }),
  buildTool({
    name: 'refresh_profile_insight',
    domain: 'profile',
    mode: 'read',
    uiLabel: '刷新画像',
    description: '重新基于当前衣橱、穿搭记录和推荐反馈计算用户偏好画像',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    handler: 'profile.read.refreshProfileInsight',
  }),
  buildTool({
    name: 'get_weather_forecast',
    domain: 'weather',
    mode: 'read',
    uiLabel: '天气预报',
    description: '读取指定城市或坐标在指定日期的天气预报；未传城市时优先使用当前会话的定位坐标，其次使用用户档案城市',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        city: { type: 'string' },
        date: {
          type: 'string',
          description: '日期，格式为 YYYY-MM-DD；不传则默认今天',
        },
        lat: { type: 'number', minimum: -90, maximum: 90 },
        lon: { type: 'number', minimum: -180, maximum: 180 },
      },
    },
    handler: 'weather.read.getWeatherForecast',
  }),
  buildTool({
    name: 'list_clothes',
    domain: 'wardrobe',
    mode: 'read',
    uiLabel: '查询衣橱',
    description: '获取当前登录用户的衣橱衣物列表（支持筛选与限制数量；默认不返回图片）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        offset: { type: 'integer', minimum: 0, maximum: 10000 },
        limit: { type: 'integer', minimum: 1, maximum: 50 },
        favoriteOnly: { type: 'boolean' },
        type: { type: 'string' },
        style: { type: 'string' },
        season: { type: 'string' },
      },
    },
    handler: 'wardrobe.read.listClothes',
  }),
  buildTool({
    name: 'get_cloth_detail',
    domain: 'wardrobe',
    mode: 'read',
    uiLabel: '衣物详情',
    description: '获取当前登录用户某一件衣物的详细信息',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        cloth_id: { type: 'integer', minimum: 1 },
      },
      required: ['cloth_id'],
    },
    handler: 'wardrobe.read.getClothDetail',
  }),
  buildTool({
    name: 'export_closet_data',
    domain: 'wardrobe',
    mode: 'read',
    uiLabel: '导出衣橱',
    description: '导出当前登录用户的衣橱数据；可选是否包含图片',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        includeImages: { type: 'boolean' },
      },
    },
    handler: 'wardrobe.read.exportClosetData',
  }),
  buildTool({
    name: 'generate_scene_suits',
    domain: 'suits',
    mode: 'read',
    uiLabel: '生成搭配',
    description: '基于当前用户衣橱与指定场景生成若干套穿搭建议（优先离线：本地规则；不返回图片）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        scene: { type: 'string' },
        limit: { type: 'integer', minimum: 1, maximum: 5 },
      },
      required: ['scene'],
    },
    handler: 'suits.read.generateSceneSuits',
  }),
  buildTool({
    name: 'list_suits',
    domain: 'suits',
    mode: 'read',
    uiLabel: '查询套装库',
    description: '获取当前用户已保存的套装列表',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        offset: { type: 'integer', minimum: 0, maximum: 10000 },
        limit: { type: 'integer', minimum: 1, maximum: 50 },
      },
    },
    handler: 'suits.read.listSavedSuits',
  }),
  buildTool({
    name: 'get_suit_detail',
    domain: 'suits',
    mode: 'read',
    uiLabel: '套装详情',
    description: '获取某一套已保存套装的详细信息，包括套装中的单品',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        suit_id: { type: 'integer', minimum: 1 },
      },
      required: ['suit_id'],
    },
    handler: 'suits.read.getSavedSuitDetail',
  }),
  buildTool({
    name: 'list_recommendations',
    domain: 'recommendations',
    mode: 'read',
    uiLabel: '查询推荐历史',
    description: '获取当前用户最近的推荐历史列表，便于查看是否已采纳、已保存为套装或已提交反馈',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        limit: { type: 'integer', minimum: 1, maximum: 20 },
      },
    },
    handler: 'recommendations.read.listRecommendations',
  }),
  buildTool({
    name: 'get_recommendation_detail',
    domain: 'recommendations',
    mode: 'read',
    uiLabel: '推荐详情',
    description: '获取某一条推荐历史的详细内容，包括推荐结果、采纳状态和反馈信息',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        recommendation_id: { type: 'integer', minimum: 1 },
      },
      required: ['recommendation_id'],
    },
    handler: 'recommendations.read.getRecommendationDetail',
  }),
  buildTool({
    name: 'list_outfit_logs',
    domain: 'outfitLogs',
    mode: 'read',
    uiLabel: '查询穿搭记录',
    description: '获取当前用户的穿搭记录列表',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        offset: { type: 'integer', minimum: 0, maximum: 10000 },
        limit: { type: 'integer', minimum: 1, maximum: 50 },
      },
    },
    handler: 'outfitLogs.read.listOutfitLogs',
  }),
  buildTool({
    name: 'get_outfit_log_detail',
    domain: 'outfitLogs',
    mode: 'read',
    uiLabel: '穿搭记录详情',
    description: '获取某条穿搭记录的详细信息，包括日期、场景、天气和单品',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        outfit_log_id: { type: 'integer', minimum: 1 },
      },
      required: ['outfit_log_id'],
    },
    handler: 'outfitLogs.read.getOutfitLogDetail',
  }),
  buildTool({
    name: 'analyze_image',
    domain: 'vision',
    mode: 'read',
    uiLabel: '图片分析',
    description: '分析当前用户消息中的图片，返回适用于穿搭问答与衣物录入的结构化结果',
    contextRequirements: ['userId', 'multimodal'],
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        attachmentIndex: {
          type: 'integer',
          minimum: 0,
          description: '当前要分析的图片索引',
        },
        question: {
          type: 'string',
          description: '用户当前关于图片的提问或关注点，可为空',
        },
      },
    },
    handler: 'vision.read.analyzeImage',
  }),
  buildTool({
    name: 'show_context_images',
    domain: 'media',
    mode: 'read',
    uiLabel: '展示图片',
    description: '基于当前对话上下文展示当前衣物、套装、穿搭记录或推荐结果的图片；适用于“给我看看图片/展示图片/发图”类请求',
    contextRequirements: ['userId', 'latestTask'],
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    handler: 'media.read.showContextImages',
  }),
  buildTool({
    name: 'show_clothes_images',
    domain: 'media',
    mode: 'read',
    uiLabel: '展示指定衣物图片',
    description: '根据指定衣物编号批量展示图片；适用于“把这三件/这几双/编号 1 2 3 的图片发我看”类请求',
    contextRequirements: ['userId'],
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        cloth_ids: {
          type: 'array',
          items: { type: 'integer', minimum: 1 },
          minItems: 1,
          maxItems: 12,
          description: '要展示图片的衣物编号列表，按传入顺序返回',
        },
      },
      required: ['cloth_ids'],
    },
    handler: 'media.read.showClothesImages',
  }),
  buildTool({
    name: 'generate_outfit_preview',
    domain: 'media',
    mode: 'read',
    uiLabel: '生成搭配预览图',
    description: '基于当前对话中的搭配草稿生成真人预览图；适用于已选上衣和下衣后让 Agent 继续生成预览图的请求',
    contextRequirements: ['userId', 'latestTask'],
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    handler: 'media.read.generateOutfitPreview',
  }),
  buildTool({
    name: 'create_cloth',
    domain: 'wardrobe',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '保存到衣橱',
    description: '创建一条衣物记录到当前用户衣橱（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        name: { type: 'string' },
        type: { type: 'string' },
        color: { type: 'string' },
        style: { type: 'string' },
        season: { type: 'string' },
        material: { type: 'string' },
        image: { type: 'string' },
      },
      required: ['name', 'type', 'color', 'style', 'season'],
    },
    confirmationDescriptor: 'wardrobe.write.createClothConfirmationDescriptor',
    handler: 'wardrobe.write.createCloth',
  }),
  buildTool({
    name: 'create_clothes_batch',
    domain: 'wardrobe',
    mode: 'write_batch',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '批量保存到衣橱',
    description: '批量创建多条衣物记录到当前用户衣橱（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        items: {
          type: 'array',
          minItems: 1,
          maxItems: 8,
          items: {
            type: 'object',
            additionalProperties: false,
            properties: {
              name: { type: 'string' },
              type: { type: 'string' },
              color: { type: 'string' },
              style: { type: 'string' },
              season: { type: 'string' },
              material: { type: 'string' },
              image: { type: 'string' },
            },
            required: ['name', 'type', 'color', 'style', 'season'],
          },
        },
      },
      required: ['items'],
    },
    confirmationDescriptor: 'wardrobe.write.createClothesBatchConfirmationDescriptor',
    handler: 'wardrobe.write.createClothesBatch',
  }),
  buildTool({
    name: 'save_suit',
    domain: 'suits',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '保存套装',
    description: '将当前推荐结果中的某一套保存为套装（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        suitIndex: { type: 'integer', minimum: 0, maximum: 4 },
        name: { type: 'string' },
        scene: { type: 'string' },
        description: { type: 'string' },
        items: {
          type: 'array',
          minItems: 2,
          maxItems: 6,
          items: { type: 'integer', minimum: 1 },
          description: '手动创建套装时使用的衣物 ID 列表',
        },
      },
    },
    confirmationDescriptor: 'suits.write.saveSuitConfirmationDescriptor',
    handler: 'suits.write.saveSuit',
  }),
  buildTool({
    name: 'update_recommendation_adoption',
    domain: 'recommendations',
    mode: 'write',
    dangerous: false,
    confirmationPolicy: 'never',
    uiLabel: '更新推荐采纳',
    description: '更新某条推荐历史的采纳状态或其是否已保存为套装/穿搭记录',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        recommendation_id: { type: 'integer', minimum: 1 },
        adopted: { type: 'boolean' },
        saved_as_suit: { type: 'boolean' },
        saved_as_outfit_log: { type: 'boolean' },
      },
      required: ['recommendation_id'],
    },
    handler: 'recommendations.write.updateRecommendationAdoption',
  }),
  buildTool({
    name: 'submit_recommendation_feedback',
    domain: 'recommendations',
    mode: 'write',
    dangerous: false,
    confirmationPolicy: 'never',
    uiLabel: '提交推荐反馈',
    description: '为某条推荐历史提交反馈结果、原因标签和备注',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        recommendation_id: { type: 'integer', minimum: 1 },
        feedbackResult: { type: 'string' },
        reasonTags: {
          type: 'array',
          items: { type: 'string' },
          maxItems: 10,
        },
        note: { type: 'string' },
      },
      required: ['recommendation_id', 'feedbackResult'],
    },
    handler: 'recommendations.write.submitRecommendationFeedback',
  }),
  buildTool({
    name: 'create_outfit_log',
    domain: 'outfitLogs',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '记录穿搭',
    description: '将当前推荐结果中的某一套记录为穿搭（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        suitIndex: { type: 'integer', minimum: 0, maximum: 4 },
      },
    },
    confirmationDescriptor: 'outfitLogs.write.createOutfitLogConfirmationDescriptor',
    handler: 'outfitLogs.write.createOutfitLog',
  }),
  buildTool({
    name: 'update_confirmation_preferences',
    domain: 'profile',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '更新确认偏好',
    description: '更新当前用户的低风险操作免确认偏好（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        lowRiskNoConfirm: { type: 'boolean' },
      },
      required: ['lowRiskNoConfirm'],
    },
    confirmationDescriptor: 'profile.write.updateConfirmationPreferencesDescriptor',
    handler: 'profile.write.updateConfirmationPreferences',
  }),
  buildTool({
    name: 'update_user_name',
    domain: 'profile',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '更新昵称',
    description: '更新当前用户昵称（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        name: { type: 'string' },
      },
      required: ['name'],
    },
    confirmationDescriptor: 'profile.write.updateUserNameDescriptor',
    handler: 'profile.write.updateUserName',
  }),
  buildTool({
    name: 'upload_user_avatar',
    domain: 'profile',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '更新头像',
    description: '更新当前用户头像（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        image: { type: 'string' },
      },
      required: ['image'],
    },
    confirmationDescriptor: 'profile.write.uploadUserAvatarDescriptor',
    handler: 'profile.write.uploadUserAvatar',
  }),
  buildTool({
    name: 'upload_character_model',
    domain: 'profile',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '更新人物模特',
    description: '更新当前用户人物模特（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        image: { type: 'string' },
      },
      required: ['image'],
    },
    confirmationDescriptor: 'profile.write.uploadCharacterModelDescriptor',
    handler: 'profile.write.uploadCharacterModel',
  }),
  buildTool({
    name: 'delete_character_model',
    domain: 'profile',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '删除人物模特',
    description: '删除当前用户人物模特（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    confirmationDescriptor: 'profile.write.deleteCharacterModelDescriptor',
    handler: 'profile.write.deleteCharacterModel',
  }),
  buildTool({
    name: 'set_cloth_favorite',
    domain: 'wardrobe',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'low-risk-optional',
    uiLabel: '更新收藏',
    description: '设置指定衣物的收藏状态（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        cloth_id: { type: 'integer', minimum: 1 },
        favorite: { type: 'boolean' },
      },
      required: ['cloth_id', 'favorite'],
    },
    confirmationDescriptor: 'wardrobe.write.setFavoriteConfirmationDescriptor',
    handler: 'wardrobe.write.setFavorite',
  }),
  buildTool({
    name: 'update_cloth_fields',
    domain: 'wardrobe',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '更新衣物信息',
    description: '更新指定衣物的基础信息字段（写操作，需要二次确认；不支持更新图片）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        cloth_id: { type: 'integer', minimum: 1 },
        name: { type: 'string' },
        type: { type: 'string' },
        color: { type: 'string' },
        style: { type: 'string' },
        season: { type: 'string' },
        material: { type: 'string' },
        favorite: { type: 'boolean' },
      },
      required: ['cloth_id'],
    },
    confirmationDescriptor: 'wardrobe.write.updateClothFieldsConfirmationDescriptor',
    handler: 'wardrobe.write.updateClothFields',
  }),
  buildTool({
    name: 'update_cloth_image',
    domain: 'wardrobe',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '更新衣物图片',
    description: '更新指定衣物的图片（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        cloth_id: { type: 'integer', minimum: 1 },
        image: { type: 'string' },
      },
      required: ['cloth_id', 'image'],
    },
    confirmationDescriptor: 'wardrobe.write.updateClothImageConfirmationDescriptor',
    handler: 'wardrobe.write.updateClothImage',
  }),
  buildTool({
    name: 'import_closet_data',
    domain: 'wardrobe',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '导入衣橱',
    description: '导入衣橱 JSON 数据到当前账号（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        items: {
          type: 'array',
          minItems: 1,
          maxItems: 100,
          items: {
            type: 'object',
            additionalProperties: false,
            properties: {
              name: { type: 'string' },
              type: { type: 'string' },
              color: { type: 'string' },
              style: { type: 'string' },
              season: { type: 'string' },
              material: { type: 'string' },
              image: { type: 'string' },
            },
            required: ['name', 'type', 'color', 'style', 'season'],
          },
        },
      },
      required: ['items'],
    },
    confirmationDescriptor: 'wardrobe.write.importClosetDataConfirmationDescriptor',
    handler: 'wardrobe.write.importClosetData',
  }),
  buildTool({
    name: 'delete_cloth',
    domain: 'wardrobe',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '删除衣物',
    description: '删除指定衣物（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        cloth_id: { type: 'integer', minimum: 1 },
      },
      required: ['cloth_id'],
    },
    confirmationDescriptor: 'wardrobe.write.deleteClothConfirmationDescriptor',
    handler: 'wardrobe.write.deleteCloth',
  }),
  buildTool({
    name: 'delete_suit',
    domain: 'suits',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '删除套装',
    description: '删除指定套装（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        suit_id: { type: 'integer', minimum: 1 },
      },
      required: ['suit_id'],
    },
    confirmationDescriptor: 'suits.write.deleteSuitConfirmationDescriptor',
    handler: 'suits.write.deleteSuit',
  }),
  buildTool({
    name: 'delete_outfit_log',
    domain: 'outfitLogs',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '删除穿搭记录',
    description: '删除指定穿搭记录（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        outfit_log_id: { type: 'integer', minimum: 1 },
      },
      required: ['outfit_log_id'],
    },
    confirmationDescriptor: 'outfitLogs.write.deleteOutfitLogConfirmationDescriptor',
    handler: 'outfitLogs.write.deleteOutfitLog',
  }),
  buildTool({
    name: 'update_outfit_log',
    domain: 'outfitLogs',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '更新穿搭记录',
    description: '更新指定穿搭记录（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        outfit_log_id: { type: 'integer', minimum: 1 },
        recommendationId: { type: 'integer', minimum: 1 },
        suitId: { type: 'integer', minimum: 1 },
        logDate: { type: 'string' },
        scene: { type: 'string' },
        weatherSummary: { type: 'string' },
        satisfaction: { type: 'integer', minimum: 0, maximum: 5 },
        source: { type: 'string' },
        note: { type: 'string' },
        items: {
          type: 'array',
          minItems: 1,
          maxItems: 8,
          items: { type: 'integer', minimum: 1 },
        },
      },
      required: ['outfit_log_id'],
    },
    confirmationDescriptor: 'outfitLogs.write.updateOutfitLogConfirmationDescriptor',
    handler: 'outfitLogs.write.updateOutfitLog',
  }),
  buildTool({
    name: 'update_user_sex',
    domain: 'profile',
    mode: 'write',
    dangerous: true,
    confirmationPolicy: 'always',
    uiLabel: '更新性别',
    description: '更新当前用户的性别设置（写操作，需要二次确认）',
    parameters: {
      type: 'object',
      additionalProperties: false,
      properties: {
        sex: { type: 'string' },
      },
      required: ['sex'],
    },
    confirmationDescriptor: 'profile.write.updateUserSexConfirmationDescriptor',
    handler: 'profile.write.updateUserSex',
  }),
]

module.exports = {
  TOOL_CATALOG,
}
