const test = require('node:test')
const assert = require('node:assert/strict')

const { listTools, getToolByName, listToolsForLlm } = require('../agent/tools/registry')
const { TOOL_DEFINITIONS, getToolDefinition } = require('../utils/toolRegistry')

test('catalog exposes all registered tool names and metadata fields', () => {
  const tools = listTools()
  const createCloth = getToolByName('create_cloth')
  const showContextImages = getToolByName('show_context_images')
  const showClothesImages = getToolByName('show_clothes_images')
  const generateOutfitPreview = getToolByName('generate_outfit_preview')
  const listSuits = getToolByName('list_suits')
  const recommendationFeedback = getToolByName('submit_recommendation_feedback')
  const refreshProfileInsight = getToolByName('refresh_profile_insight')

  assert.ok(Array.isArray(tools))
  assert.ok(tools.length >= 10)
  assert.ok(createCloth)
  assert.ok(showContextImages)
  assert.ok(showClothesImages)
  assert.ok(generateOutfitPreview)
  assert.ok(listSuits)
  assert.ok(recommendationFeedback)
  assert.ok(refreshProfileInsight)
  assert.equal(createCloth.domain, 'wardrobe')
  assert.equal(createCloth.mode, 'write')
  assert.equal(createCloth.confirmationPolicy, 'always')
  assert.equal(createCloth.uiLabel, '保存到衣橱')
  assert.equal(showContextImages.domain, 'media')
  assert.equal(showContextImages.mode, 'read')
  assert.equal(showClothesImages.domain, 'media')
  assert.equal(showClothesImages.mode, 'read')
  assert.equal(generateOutfitPreview.domain, 'media')
  assert.equal(generateOutfitPreview.mode, 'read')
  assert.equal(listSuits.domain, 'suits')
  assert.equal(listSuits.mode, 'read')
  assert.equal(recommendationFeedback.domain, 'recommendations')
  assert.equal(recommendationFeedback.confirmationPolicy, 'never')
  assert.equal(refreshProfileInsight.domain, 'profile')
  assert.equal(refreshProfileInsight.mode, 'read')
  assert.ok(createCloth.resultPresenter)
  assert.ok(createCloth.confirmationDescriptor)
})

test('registry can return llm-visible tools for current context', () => {
  const tools = listToolsForLlm({ intent: 'clothing', hasImage: false })
  assert.ok(tools.find((tool) => tool.name === 'list_clothes'))
  assert.ok(tools.find((tool) => tool.name === 'get_weather_forecast'))
  assert.ok(tools.find((tool) => tool.name === 'create_cloth'))
  assert.ok(tools.find((tool) => tool.name === 'list_suits'))
  assert.ok(tools.find((tool) => tool.name === 'list_outfit_logs'))
  assert.ok(tools.find((tool) => tool.name === 'list_recommendations'))
  assert.ok(tools.find((tool) => tool.name === 'submit_recommendation_feedback'))
  assert.ok(tools.find((tool) => tool.name === 'show_context_images'))
  assert.ok(tools.find((tool) => tool.name === 'show_clothes_images'))
  assert.ok(tools.find((tool) => tool.name === 'generate_outfit_preview'))
  assert.ok(!tools.find((tool) => tool.name === 'analyze_image'))

  const imageTools = listToolsForLlm({ intent: 'clothing', hasImage: true })
  assert.ok(imageTools.find((tool) => tool.name === 'analyze_image'))
})

test('toolRegistry compatibility exports definitions from catalog', () => {
  const createClothFromCompat = getToolDefinition('create_cloth')
  const createClothFromCatalog = getToolByName('create_cloth')
  const imageFromCompat = getToolDefinition('analyze_image')
  const weatherFromCompat = getToolDefinition('get_weather_forecast')
  const recommendationFromCompat = getToolDefinition('submit_recommendation_feedback')

  assert.ok(Array.isArray(TOOL_DEFINITIONS))
  assert.equal(createClothFromCompat?.name, createClothFromCatalog?.name)
  assert.deepEqual(createClothFromCompat?.parameters, createClothFromCatalog?.parameters)
  assert.equal(imageFromCompat?.name, 'analyze_image')
  assert.equal(weatherFromCompat?.name, 'get_weather_forecast')
  assert.equal(recommendationFromCompat?.name, 'submit_recommendation_feedback')
})
