const test = require('node:test')
const assert = require('node:assert/strict')

const { listTools, getToolByName, listToolsForLlm } = require('../agent/tools/registry')
const { TOOL_DEFINITIONS, getToolDefinition } = require('../utils/toolRegistry')

test('catalog exposes all registered tool names and metadata fields', () => {
  const tools = listTools()
  const createCloth = getToolByName('create_cloth')
  const exportClosetData = getToolByName('export_closet_data')
  const importClosetData = getToolByName('import_closet_data')
  const updateClothImage = getToolByName('update_cloth_image')
  const updateUserName = getToolByName('update_user_name')
  const uploadUserAvatar = getToolByName('upload_user_avatar')
  const uploadCharacterModel = getToolByName('upload_character_model')
  const deleteCharacterModel = getToolByName('delete_character_model')
  const showContextImages = getToolByName('show_context_images')
  const showClothesImages = getToolByName('show_clothes_images')
  const generateOutfitPreview = getToolByName('generate_outfit_preview')
  const listSuits = getToolByName('list_suits')
  const recommendationFeedback = getToolByName('submit_recommendation_feedback')
  const refreshProfileInsight = getToolByName('refresh_profile_insight')
  const updateOutfitLog = getToolByName('update_outfit_log')

  assert.ok(Array.isArray(tools))
  assert.ok(tools.length >= 10)
  assert.ok(createCloth)
  assert.ok(exportClosetData)
  assert.ok(importClosetData)
  assert.ok(updateClothImage)
  assert.ok(updateUserName)
  assert.ok(uploadUserAvatar)
  assert.ok(uploadCharacterModel)
  assert.ok(deleteCharacterModel)
  assert.ok(showContextImages)
  assert.ok(showClothesImages)
  assert.ok(generateOutfitPreview)
  assert.ok(listSuits)
  assert.ok(recommendationFeedback)
  assert.ok(refreshProfileInsight)
  assert.ok(updateOutfitLog)
  assert.equal(createCloth.domain, 'wardrobe')
  assert.equal(createCloth.mode, 'write')
  assert.equal(createCloth.confirmationPolicy, 'always')
  assert.equal(createCloth.uiLabel, '保存到衣橱')
  assert.equal(exportClosetData.domain, 'wardrobe')
  assert.equal(exportClosetData.mode, 'read')
  assert.equal(importClosetData.domain, 'wardrobe')
  assert.equal(importClosetData.mode, 'write')
  assert.equal(importClosetData.confirmationPolicy, 'always')
  assert.equal(updateClothImage.domain, 'wardrobe')
  assert.equal(updateClothImage.mode, 'write')
  assert.equal(updateClothImage.confirmationPolicy, 'always')
  assert.equal(updateUserName.domain, 'profile')
  assert.equal(updateUserName.mode, 'write')
  assert.equal(uploadUserAvatar.domain, 'profile')
  assert.equal(uploadUserAvatar.confirmationPolicy, 'always')
  assert.equal(uploadCharacterModel.domain, 'profile')
  assert.equal(deleteCharacterModel.domain, 'profile')
  assert.equal(showContextImages.domain, 'media')
  assert.equal(showContextImages.mode, 'read')
  assert.equal(showClothesImages.domain, 'media')
  assert.equal(showClothesImages.mode, 'read')
  assert.equal(generateOutfitPreview.domain, 'media')
  assert.equal(generateOutfitPreview.mode, 'read')
  assert.equal(listSuits.domain, 'suits')
  assert.equal(listSuits.mode, 'read')
  assert.equal(recommendationFeedback.domain, 'recommendations')
  assert.equal(recommendationFeedback.confirmationPolicy, 'never')
  assert.equal(refreshProfileInsight.domain, 'profile')
  assert.equal(refreshProfileInsight.mode, 'read')
  assert.equal(updateOutfitLog.domain, 'outfitLogs')
  assert.equal(updateOutfitLog.mode, 'write')
  assert.equal(updateOutfitLog.confirmationPolicy, 'always')
  assert.ok(createCloth.resultPresenter)
  assert.ok(createCloth.confirmationDescriptor)
  assert.ok(importClosetData.confirmationDescriptor)
  assert.ok(updateClothImage.confirmationDescriptor)
  assert.ok(updateUserName.confirmationDescriptor)
  assert.ok(uploadUserAvatar.confirmationDescriptor)
  assert.ok(uploadCharacterModel.confirmationDescriptor)
  assert.ok(deleteCharacterModel.confirmationDescriptor)
  assert.ok(updateOutfitLog.confirmationDescriptor)
})

test('registry can return llm-visible tools for current context', () => {
  const tools = listToolsForLlm({ intent: 'clothing', hasImage: false })
  assert.ok(tools.find((tool) => tool.name === 'list_clothes'))
  assert.ok(tools.find((tool) => tool.name === 'get_weather_forecast'))
  assert.ok(tools.find((tool) => tool.name === 'create_cloth'))
  assert.ok(tools.find((tool) => tool.name === 'list_suits'))
  assert.ok(tools.find((tool) => tool.name === 'list_outfit_logs'))
  assert.ok(tools.find((tool) => tool.name === 'list_recommendations'))
  assert.ok(tools.find((tool) => tool.name === 'submit_recommendation_feedback'))
  assert.ok(tools.find((tool) => tool.name === 'export_closet_data'))
  assert.ok(tools.find((tool) => tool.name === 'import_closet_data'))
  assert.ok(tools.find((tool) => tool.name === 'update_cloth_image'))
  assert.ok(tools.find((tool) => tool.name === 'update_user_name'))
  assert.ok(tools.find((tool) => tool.name === 'upload_user_avatar'))
  assert.ok(tools.find((tool) => tool.name === 'upload_character_model'))
  assert.ok(tools.find((tool) => tool.name === 'delete_character_model'))
  assert.ok(tools.find((tool) => tool.name === 'update_outfit_log'))
  assert.ok(tools.find((tool) => tool.name === 'show_context_images'))
  assert.ok(tools.find((tool) => tool.name === 'show_clothes_images'))
  assert.ok(tools.find((tool) => tool.name === 'generate_outfit_preview'))
  assert.ok(!tools.find((tool) => tool.name === 'analyze_image'))

  const imageTools = listToolsForLlm({ intent: 'clothing', hasImage: true })
  assert.ok(imageTools.find((tool) => tool.name === 'analyze_image'))
})

test('toolRegistry compatibility exports definitions from catalog', () => {
  const createClothFromCompat = getToolDefinition('create_cloth')
  const createClothFromCatalog = getToolByName('create_cloth')
  const exportClosetDataFromCompat = getToolDefinition('export_closet_data')
  const importClosetDataFromCompat = getToolDefinition('import_closet_data')
  const updateClothImageFromCompat = getToolDefinition('update_cloth_image')
  const updateUserNameFromCompat = getToolDefinition('update_user_name')
  const uploadUserAvatarFromCompat = getToolDefinition('upload_user_avatar')
  const uploadCharacterModelFromCompat = getToolDefinition('upload_character_model')
  const deleteCharacterModelFromCompat = getToolDefinition('delete_character_model')
  const updateOutfitLogFromCompat = getToolDefinition('update_outfit_log')
  const imageFromCompat = getToolDefinition('analyze_image')
  const weatherFromCompat = getToolDefinition('get_weather_forecast')
  const recommendationFromCompat = getToolDefinition('submit_recommendation_feedback')

  assert.ok(Array.isArray(TOOL_DEFINITIONS))
  assert.equal(createClothFromCompat?.name, createClothFromCatalog?.name)
  assert.deepEqual(createClothFromCompat?.parameters, createClothFromCatalog?.parameters)
  assert.equal(exportClosetDataFromCompat?.name, 'export_closet_data')
  assert.equal(importClosetDataFromCompat?.name, 'import_closet_data')
  assert.equal(updateClothImageFromCompat?.name, 'update_cloth_image')
  assert.equal(updateUserNameFromCompat?.name, 'update_user_name')
  assert.equal(uploadUserAvatarFromCompat?.name, 'upload_user_avatar')
  assert.equal(uploadCharacterModelFromCompat?.name, 'upload_character_model')
  assert.equal(deleteCharacterModelFromCompat?.name, 'delete_character_model')
  assert.equal(updateOutfitLogFromCompat?.name, 'update_outfit_log')
  assert.equal(imageFromCompat?.name, 'analyze_image')
  assert.equal(weatherFromCompat?.name, 'get_weather_forecast')
  assert.equal(recommendationFromCompat?.name, 'submit_recommendation_feedback')
})
